name: 'Run Pkg.build'
description: 'Run the build step in a Julia package'
author: 'David Anthoff'

branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  project:
    description: 'Value passed to the --project flag. The default value is the repository root: "@."'
    default: '@.'
  precompile:
    description: 'Whether to allow auto-precompilation (via the `JULIA_PKG_PRECOMPILE_AUTO` env var). Options: yes | no. Default value: no.'
    default: 'no'
  propagate_registry_preference:
    description: 'Propagate the JULIA_PKG_SERVER_REGISTRY_PREFERENCE environment variable to future steps'
    default: 'yes'

runs:
  using: 'composite'
  steps:
  - run: |
      import Pkg
      pref_key = "JULIA_PKG_SERVER_REGISTRY_PREFERENCE"
      pref_value = strip(get(ENV, pref_key, "eager"))
      ENV[pref_key] = pref_value
      input = strip(ENV["PROPAGATE_INPUT"])
      if input == "yes"
          propagate = true
      elseif input == "no"
          propagate = false
      else
          msg = "Invalid value for the `propagate_registry_preference` input: $(input)"
          error(msg)
      end
      delete!(ENV, "PROPAGATE_INPUT");
      Pkg.Registry.add("General")
      Pkg.Registry.update()
      if VERSION >= v"1.1.0-rc1"
          Pkg.build(; verbose=true)
      else
          Pkg.build()
      end
      if propagate
          # Set the JULIA_PKG_SERVER_REGISTRY_PREFERENCE environment variable
          # for future steps in this job.
          # Note: this will apply to the steps that run after
          # the `- uses: julia-actions/julia-buildpkg` step.
          open(ENV["GITHUB_ENV"], "a") do io
              println(io, "$(pref_key)=$(pref_value)")
          end
      end
    shell: julia --color=yes --project=${{ inputs.project }} {0}
    env:
      PROPAGATE_INPUT: '${{ inputs.propagate_registry_preference }}'
      JULIA_PKG_PRECOMPILE_AUTO: "${{ inputs.precompile }}"
