name: 'Run Pkg.build'
description: 'Run the build step in a Julia package'
author: 'David Anthoff'

branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  project:
    description: 'Value passed to the --project flag. The default value is the repository root: "@."'
    default: '@.'
  precompile:
    description: 'Whether to allow auto-precompilation (via the `JULIA_PKG_PRECOMPILE_AUTO` env var). Options: yes | no. Default value: no.'
    default: 'no'

runs:
  using: 'composite'
  steps:
    # Occasionally, there are rather large delays (> a few hours)
    # between the time a package is registered in General and
    # propagated to pkg.julialang.org.  We can avoid this by manually
    # cloning ~/.julia/registries/General/ in Julia 1.5 and later.
    # See:
    # * https://github.com/JuliaLang/Pkg.jl/issues/2011
    # * https://github.com/JuliaRegistries/General/issues/16777
    # * https://github.com/JuliaPackaging/PkgServer.jl/issues/60
  - run: julia --color=yes "$GITHUB_ACTION_PATH"/add_general_registry.jl
    shell: bash
    env:
      # We set `JULIA_PKG_SERVER` only for this step to enforce
      # `Pkg.Registry.add` to use Git.  This way, Pkg.jl can send
      # the request metadata to pkg.julialang.org when installing
      # packages via `Pkg.test`.
      JULIA_PKG_SERVER: ""

  - run: julia --color=yes --project=${{ inputs.project }} -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end'
    shell: bash
    env:
      JULIA_PKG_PRECOMPILE_AUTO: "${{ inputs.precompile }}"
