name: 'Run Pkg.build'
description: 'Run the build step in a Julia package'
author: 'David Anthoff'

branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  project:
    description: 'Value passed to the --project flag. The default value is the repository root: "@."'
    default: '@.'
  precompile:
    description: 'Whether to allow auto-precompilation (via the `JULIA_PKG_PRECOMPILE_AUTO` env var). Options: yes | no. Default value: no.'
    default: 'no'
  propagate_registry_preference:
    description: 'Propagate the JULIA_PKG_SERVER_REGISTRY_PREFERENCE environment variable to all future steps'
    default: 'yes'

runs:
  using: 'composite'
  steps:
  - run: |
      reg_pref = strip(get(ENV, "JULIA_PKG_SERVER_REGISTRY_PREFERENCE", "eager"))
      input = strip(get(ENV, "FOO", ""))
      if input == "yes"
          propagate = true
      elseif foo == "no"
          propagate = false
      else
          msg = "Invalid value for the `propagate_registry_preference` input: $(input)"
          error(msg)
      end
      if
          open(ENV["GITHUB_ENV"], "a") do io
              println(io, "JULIA_PKG_SERVER_REGISTRY_PREFERENCE=$(reg_pref)")
          end
      end
    shell: julia --color=yes {0}
    env:
      PROPAGATE_INPUT: '
    echo "{environment_variable_name}={value}" >> $GITHUB_ENV
    if: inputs.project == 'yes'

  - run: julia --color=yes --project=${{ inputs.project }} -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end'
    shell: bash
    env:
      JULIA_PKG_PRECOMPILE_AUTO: "${{ inputs.precompile }}"
