name: 'Run Pkg.build'
description: 'Run the build step in a Julia package'
author: 'David Anthoff'

branding:
  icon: 'box'
  color: 'gray-dark'

inputs:
  project:
    description: 'Value passed to the --project flag. The default value is the repository root: "@."'
    default: '@.'
  prefix:
    description: 'Value inserted in front of the julia command, e.g. for running xvfb-run julia [...]'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    # Occasionally, there are rather large delays (> a few hours)
    # between the time a package is registered in General and
    # propagated to pkg.julialang.org.  We can avoid this by manually
    # cloning ~/.julia/registries/General/ in Julia 1.5 and later.
    # See:
    # * https://github.com/JuliaLang/Pkg.jl/issues/2011
    # * https://github.com/JuliaRegistries/General/issues/16777
    # * https://github.com/JuliaPackaging/PkgServer.jl/issues/60
  - run: julia --color=yes "$GITHUB_ACTION_PATH"/add_general_registry.jl
    shell: bash
    env:
      # We set `JULIA_PKG_SERVER` only for this step to enforce
      # `Pkg.Registry.add` to use Git.  This way, Pkg.jl can send
      # the request metadata to pkg.julialang.org when installing
      # packages via `Pkg.test`.
      JULIA_PKG_SERVER: ""

  - run: |
        # The Julia command that will be executed
        julia_cmd=( julia --color=yes --project=${{ inputs.project }} -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end' )

        # Add the prefix in front of the command if there is one
        prefix="${{ inputs.prefix }}"
        [[ -n $prefix ]] && julia_cmd=( "$prefix" "${julia_cmd[@]}" )

        # Run the Julia command
        "${julia_cmd[@]}"
    shell: bash
